In [9]:
import numpy as np

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
np.ones(2,dtype='int')

array([1, 1])

In [12]:
np.zeros((5,20),int).reshape(5,20).T

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [13]:
np.identity(10,int).T

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [14]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [15]:
np.linspace(0,64,9)

array([ 0.,  8., 16., 24., 32., 40., 48., 56., 64.])

## Random Numbers

In [16]:
rng=np.random.default_rng(616)
rng.random(10)

array([0.39682145, 0.86568572, 0.46040359, 0.30599848, 0.57381588,
       0.08888468, 0.88194347, 0.73228387, 0.73215182, 0.56233394])

In [17]:
rng.integers(0,10,100)

array([8, 3, 6, 0, 3, 3, 1, 2, 2, 4, 9, 1, 2, 5, 1, 8, 9, 0, 3, 1, 5, 8,
       0, 6, 1, 7, 0, 7, 6, 0, 3, 7, 1, 9, 4, 1, 6, 1, 4, 4, 9, 5, 3, 4,
       7, 8, 3, 3, 5, 0, 4, 9, 9, 5, 6, 5, 8, 2, 3, 0, 0, 8, 3, 8, 4, 8,
       8, 9, 7, 3, 8, 4, 9, 2, 6, 3, 0, 3, 2, 0, 0, 4, 9, 5, 4, 1, 8, 2,
       7, 7, 1, 2, 2, 4, 1, 6, 7, 3, 7, 5], dtype=int64)

In [18]:
rng.normal(50,5,3)

array([53.53115044, 46.35468178, 46.1580894 ])

In [20]:
rng=np.random.default_rng(200)
rng.random(10)


array([0.64683414, 0.66391997, 0.02990165, 0.17783134, 0.57349665,
       0.55116402, 0.52692044, 0.37424281, 0.0607941 , 0.36999257])

#    # indexing and slicing

In [21]:
import numpy as np

In [22]:
integer_array=np.arange(12)

In [23]:
integer_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
integer_array[2]

2

In [25]:
integer_array[-2]

10

In [26]:
integer_array[:5]

array([0, 1, 2, 3, 4])

In [27]:
integer_array[5:]

array([ 5,  6,  7,  8,  9, 10, 11])

In [28]:
integer_array[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [29]:
integer_array[::2]

array([ 0,  2,  4,  6,  8, 10])

In [31]:
new_array=integer_array.reshape(3,4)
new_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
new_array[:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
new_array[1:,:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
new_array[:,3]

array([ 3,  7, 11])

In [45]:
new_array[2,3]

11

In [47]:
new_array[0,0]

0