In [ ]:
import numpy as np

In [ ]:
y=np.array([0,1,2,3])
y

array([0, 1, 2, 3])

In [ ]:
y.ndim

1

In [ ]:
y.size

4

In [ ]:
y.dtype

dtype('int64')

In [ ]:
y.shape

(4,)

In [ ]:
y.reshape(2,2)

array([[0, 1],
       [2, 3]])

In [ ]:
rng=np.random.default_rng()
x=rng.random(10)
x

array([0.41472002, 0.14857899, 0.23231762, 0.8569078 , 0.35578472,
       0.91215934, 0.12227668, 0.35592991, 0.20276551, 0.52791481])

In [ ]:
x=np.array([[1,3,5,7,9],[2,4,6,8,10]])
x

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [ ]:
len(x)


2

In [ ]:
x.shape

(2, 5)

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
np.linspace(0,1,5).round(1)

array([0. , 0.2, 0.5, 0.8, 1. ])