In [2]:
import numpy as np

In [3]:
array=np.array(range(5))

In [4]:
array

array([0, 1, 2, 3, 4])

In [5]:
array_2d=np.array([range(5),range(5)])
array_2d

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [6]:
array.shape

(5,)

In [7]:
array_2d.shape

(2, 5)

In [8]:
array.size

5

In [9]:
array_2d.size

10

In [10]:
array_2d.T.shape

(5, 2)

In [11]:
array.ndim

1

In [12]:
array_2d.ndim

2

In [13]:
array.dtype

dtype('int32')

In [14]:
array_2d.dtype

dtype('int32')

In [15]:
np.array(['i', 'love', 'python'])

array(['i', 'love', 'python'], dtype='<U6')

In [16]:
my_list=[x*10 for x in range(1,11)]

In [17]:
array2=np.array(my_list)

In [18]:
array2

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [19]:
array2.dtype

dtype('int32')

In [20]:
array2.shape

(10,)

In [21]:
array2.size

10

In [22]:
array=np.random.default_rng(2022)
array.random(10).reshape(10,1)

array([[0.24742606],
       [0.09299006],
       [0.61176337],
       [0.06066207],
       [0.66103343],
       [0.75515778],
       [0.1108689 ],
       [0.04305584],
       [0.41441747],
       [0.98862926]])

In [23]:
array.normal(20,2,2)

array([17.11953284, 20.15777538])

In [35]:
sales=np.arange(0,10).reshape(2,5)
sales

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [42]:
sales +5

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [43]:
quantity=sales[0,]
price=sales[1,]
quantity*price

array([ 0,  6, 14, 24, 36])

In [45]:
import numpy as np
rng=np.random.default_rng(616)
inventory=rng.integers(0,100,10)
inventory

array([39, 39, 93, 86, 48, 46, 48, 30, 11, 57], dtype=int64)

In [46]:
inventory-24

array([ 15,  15,  69,  62,  24,  22,  24,   6, -13,  33], dtype=int64)

In [47]:
inventory*10

array([390, 390, 930, 860, 480, 460, 480, 300, 110, 570], dtype=int64)

In [55]:
inventory/2

array([19.5, 19.5, 46.5, 43. , 24. , 23. , 24. , 15. ,  5.5, 28.5])

In [56]:
price=(rng.random(10)*10).round(2)
price

array([3.74, 0.37, 4.37, 5.7 , 1.97, 2.87, 7.76, 2.24, 4.91, 6.35])

In [57]:
price*inventory

array([145.86,  14.43, 406.41, 490.2 ,  94.56, 132.02, 372.48,  67.2 ,
        54.01, 361.95])