### Package Imports

In [2]:
import numpy as np

# Assignment 1: Array Basics

Hi there,

Can you import Numpy and convert the following list comprehension (I just learned about comprehensions in an awesome course by Maven) into an array?

Once you've done that report the following about the array:
* The number of dimensions 
* The shape
* The number of elements in the array
* The type of data contained inside

In [3]:
my_list=[[10,20,30,40,50],[60,70,80,90,100]] 
array=np.array(my_list)
array

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [4]:
array.ndim

2

In [5]:
array.shape

(2, 5)

In [6]:
array.size

10

In [7]:
array.dtype

dtype('int32')

In [8]:
array.reshape(5,2)

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

# Assignment 2: Array Creation

Thanks for your help with the first piece - I'm starting to understand some of the key differences between base Python data types and NumPy arrays. 

Does NumPy have anything like the range() function from base Python?

If so: 
* create the same array from assignment 1 using a NumPy function. 
* Make it 5 rows and 2 columns. 
* It's ok if the datatype is float or int.

In [9]:
myarray=np.linspace(10,100,10).reshape(5,2)
myarray

array([[ 10.,  20.],
       [ 30.,  40.],
       [ 50.,  60.],
       [ 70.,  80.],
       [ 90., 100.]])

In [10]:
myarray=np.arange(10,101,10).reshape(5,2)
myarray

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [11]:
myarray=(np.arange(1,11)*10).reshape(5,2)
myarray

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

Looking good so far! One of our data scientists asked about random number generation in NumPy.

Can you create a 3x3 array of random numbers between 0 and 1? Use a random state of 2022.

Store the random array in a variable called `random_array`.

In [12]:
rng=np.random.default_rng(2022)
random_array=rng.random(9).reshape(3,3)
random_array

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])

In [13]:
rng.normal(20,50,10)

array([-126.56242518,  -52.01167905,   23.9443846 ,   49.28204015,
        103.38580539,  -37.04464829,    9.50499685,   44.84060206,
         70.99858562,  -24.14346849])

In [14]:
rng.integers(5)

3

# Assignment 3: Accessing Array Data


Slice and index the `random_array` we created in the previous exercise. Perform the following:

* Grab the first two 'rows' of the array
* Grab the entire first column
* Finally, grab the second selement of the third row.

Thanks!


In [15]:
random_array=rng.random(9).reshape(3,3)
random_array

array([[0.2494223 , 0.06229007, 0.94479027],
       [0.65028587, 0.32167568, 0.08336384],
       [0.21924361, 0.08417791, 0.05213927]])

In [16]:
random_array[:2,:]

array([[0.2494223 , 0.06229007, 0.94479027],
       [0.65028587, 0.32167568, 0.08336384]])

In [17]:
 random_array[:,0]

array([0.2494223 , 0.65028587, 0.21924361])

In [19]:
random_array[2,1]

0.0841779096255445

# Assignment 4: Arithmetic Operations

The creativity of our marketing team knows no bounds!

They've asked us to come up with a simple algorithm to provide a random discount to our list of prices below. 

Before we do that, 

* Add a 5 dollar shipping fee to each price. Call this array `total`.

Once we have that, we want to use the random_array created in assignment 2 and apply them to the 6 prices.

* Grab the first 6 numbers from `random_array`, reshape it to one dimension. Call this `discount_pct`.
* Subtract `discount_pct` FROM 1, store this in `pct_owed`.
* Multiply `pct_owed` by `total` to get the final amount owed.

In [20]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])


In [21]:
total=prices+5
total

array([ 10.99,  11.99,  27.49, 104.99,   9.99,  54.99])

In [22]:
discount_pct=random_array.reshape(9)[:7]
discount_pct

array([0.2494223 , 0.06229007, 0.94479027, 0.65028587, 0.32167568,
       0.08336384, 0.21924361])

In [23]:
pct_owed=1-discount_pct
pct_owed

array([0.7505777 , 0.93770993, 0.05520973, 0.34971413, 0.67832432,
       0.91663616, 0.78075639])

In [24]:
fnl_amt_owed=pct_owed*discount_pct
fnl_amt_owed

array([0.18721081, 0.05841002, 0.05216161, 0.22741416, 0.21820044,
       0.07641431, 0.17117585])

In [29]:
print(discount_pct)
print(pct_owed)
print(fnl_amt_owed.round(2))

[0.2494223  0.06229007 0.94479027 0.65028587 0.32167568 0.08336384
 0.21924361]
[0.7505777  0.93770993 0.05520973 0.34971413 0.67832432 0.91663616
 0.78075639]
[0.19 0.06 0.05 0.23 0.22 0.08 0.17]


# Assignment 5: Filtering Arrays

Filter the product array to only include those with prices greater than 25.

Modify your logic to include cola, despite it not having a price greater than 25. 
Store the elements returned in an array called `fancy_feast_special`.

Next, create a shipping cost array where the cost is 0 if price is greater than 20, and 5 if not. 

In [ ]:
products = np.array(
    ["salad", "bread", "mustard", "rare tomato", "cola", "gourmet ice cream"]
)

products

# Assignment 6: Aggregating and Sorting Arrays

First, grab the top 3 highest priced items in our list. 

Then, calculated the mean, min, max, and median of the top three prices.

Finally, calculate the number of unique price tiers in our `price_tiers` array.

In [ ]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])

prices

In [ ]:
price_tiers = np.array(["budget", "budget", "mid-tier", "luxury", "mid-tier", "luxury"])

# Assignment 7: Bringing it All Together

Ok, final NumPy task - let's read in some data with the help of Pandas.

Our data scientist provided the code to read in a csv as a Pandas dataframe, and has converted the two columns of interest to arrays.

* Filter `sales_array` down to only sales where the product family was produce. 

* Then, randomly sample roughly half (random number < .5) of the produce sales and report the mean and median sales. Use a random seed of 2022.

* Finally, create a new array that has the values 'above_both', 'above_median', and 'below_both' based on whether the sales were above the median and mean of the sample, just above the median of the sample, or below both the median and mean of the sample. 

In [2]:
import pandas as pd
import numpy as np

retail_df = pd.read_csv(
    "C:\\Users\\pc\\Desktop\\retail.csv", skiprows=range(1, 11000), nrows=1000
)

family_array = np.array(retail_df["family"])
sales_array = np.array(retail_df["sales"])


In [3]:
sales_array[family_array=='PRODUCE']


array([1662.394,  447.064, 2423.944,  962.866, 1236.404,  298.441,
       1077.44 , 3404.531,  962.96 ,  279.505, 1852.786, 1089.319,
        726.516, 7860.031,  446.038, 1155.385,  120.202,  862.092,
        473.952,  254.263, 1272.755, 2775.771, 2030.762, 1657.432,
       2339.906,  722.333, 1567.843, 2458.456,  673.885, 8834.15 ])

In [4]:
rng=np.random.default_rng(2022)
random_array=rng.random(30)
random_array

array([0.24742606, 0.09299006, 0.61176337, 0.06066207, 0.66103343,
       0.75515778, 0.1108689 , 0.04305584, 0.41441747, 0.98862926,
       0.96919869, 0.25697153, 0.55876211, 0.24234798, 0.32202029,
       0.89135975, 0.94611366, 0.72253931, 0.92847437, 0.99608701,
       0.2494223 , 0.06229007, 0.94479027, 0.65028587, 0.32167568,
       0.08336384, 0.21924361, 0.08417791, 0.05213927, 0.20525022])